// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPQ7rYZ8-Z0SnSUuxwPnU0xB9wLB2Ejqw',
    appId: '1:709259936363:web:b4831dc2b2a1dbbcf4a72e',
    messagingSenderId: '709259936363',
    projectId: 'flash-cc048',
    authDomain: 'flash-cc048.firebaseapp.com',
    storageBucket: 'flash-cc048.firebasestorage.app',
    measurementId: 'G-QJC0H4V0G5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbo5JnSkGfPSMU4RtkAavc9oHZH0Zz-r4',
    appId: '1:709259936363:android:6243138f2c637140f4a72e',
    messagingSenderId: '709259936363',
    projectId: 'flash-cc048',
    storageBucket: 'flash-cc048.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Jxl_xAEVjJIOIjlClW1rwK_Ef_qOL9U',
    appId: '1:709259936363:ios:f88648eb6e78c9acf4a72e',
    messagingSenderId: '709259936363',
    projectId: 'flash-cc048',
    storageBucket: 'flash-cc048.firebasestorage.app',
    iosBundleId: 'com.example.depifinalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Jxl_xAEVjJIOIjlClW1rwK_Ef_qOL9U',
    appId: '1:709259936363:ios:f88648eb6e78c9acf4a72e',
    messagingSenderId: '709259936363',
    projectId: 'flash-cc048',
    storageBucket: 'flash-cc048.firebasestorage.app',
    iosBundleId: 'com.example.depifinalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPQ7rYZ8-Z0SnSUuxwPnU0xB9wLB2Ejqw',
    appId: '1:709259936363:web:1a4907ac2c39d487f4a72e',
    messagingSenderId: '709259936363',
    projectId: 'flash-cc048',
    authDomain: 'flash-cc048.firebaseapp.com',
    storageBucket: 'flash-cc048.firebasestorage.app',
    measurementId: 'G-VWBPH6SHGZ',
  );
}
